name: MLOps Pipeline (Smoke)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Invoke SageMaker endpoint
        env:
          SAGEMAKER_ENDPOINT_NAME: ${{ secrets.SAGEMAKER_ENDPOINT_NAME }}
        run: |
          python - <<'PY'
          import os, boto3
          endpoint = os.environ.get("SAGEMAKER_ENDPOINT_NAME")
          if not endpoint:
            raise SystemExit("Missing secret SAGEMAKER_ENDPOINT_NAME")
          rt = boto3.client("sagemaker-runtime", region_name="us-east-1")
          resp = rt.invoke_endpoint(
            EndpointName=endpoint,
            ContentType="text/csv",
            Accept="application/json",
            Body=b"3,1,34,0,0,7.8292,2",
          )
          print(resp["Body"].read().decode())
          PY
