name: MLOps Pipeline (Smoke)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # If your secrets are under an Environment (e.g., Production), uncomment:
    # environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Preflight: ensure required secrets exist
        run: |
          [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ] || { echo "::error:: Missing repo secret AWS_ACCESS_KEY_ID"; exit 1; }
          [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ] || { echo "::error:: Missing repo secret AWS_SECRET_ACCESS_KEY"; exit 1; }
          [ -n "${{ secrets.SAGEMAKER_ENDPOINT_NAME }}" ] || { echo "::error:: Missing repo secret SAGEMAKER_ENDPOINT_NAME"; exit 1; }

      - name: Configure AWS credentials (sets region, too)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Invoke serverless endpoint
        env:
          SAGEMAKER_ENDPOINT_NAME: ${{ secrets.SAGEMAKER_ENDPOINT_NAME }}
        run: |
          python - <<'PY'
          import os, boto3
          rt = boto3.client("sagemaker-runtime", region_name="us-east-1")
          resp = rt.invoke_endpoint(
              EndpointName=os.environ["SAGEMAKER_ENDPOINT_NAME"],
              ContentType="text/csv",
              Accept="application/json",
              Body=b"3,1,34,0,0,7.8292,2",
          )
          print(resp["Body"].read().decode())
          PY

