name: MLOps Pipeline (Smoke)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SAGEMAKER_ENDPOINT_NAME: ${{ secrets.SAGEMAKER_ENDPOINT_NAME }}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Invoke serverless endpoint
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          python - <<'PY'
          import os, boto3
          rt = boto3.client("sagemaker-runtime", region_name=os.environ["AWS_REGION"])
          row = "3,1,34,0,0,7.8292,2"
          resp = rt.invoke_endpoint(
              EndpointName=os.environ["SAGEMAKER_ENDPOINT_NAME"],
              ContentType="text/csv",
              Accept="application/json",
              Body=row.encode("utf-8"),
          )
          print(resp["Body"].read().decode())
          PY

